### ISSUE TITLE
Icecrown LordMarrowgar and Deathwhisper 

### ISSUE THREAD

**Issue by johngitboy** [Ayaro1/DBM_Warmane_Icecrown#1]
Some info may be useful to you.
Info: I did my icc 10nm raid on Lordaeron,I'm sure that in LordMarrowgar's battle, timerWhirlwind changed from 20s to 30s, and timerWhirlwindCD is 60s,not 90s.

Question:In Deathwhisper lua ,I thought if there're some errors in these following codes  ?
```
if not mod:IsDifficulty("normal10") then
		timerDominateMindCD:Start(30)		-- Sometimes 1 fails at the start, then the next will be applied 70 secs after start ?? :S
	end
	timerDominateMindCD:Start(-13-delay)  -- Custom adjustment to Heroic25
	if self.Options.RemoveDruidBuff then  -- Edit to automaticly remove Mark/Gift of the Wild on entering combat
		mod:ScheduleMethod(24, "RemoveBuffs")
	end
```

**Comment by Ayaro1** [comment]
Hi,

Quick copy/paste from the Marrowgar code:
local timerWhirlwindCD      = mod:NewCDTimer(90, 69076)
local timerWhirlwind        = mod:NewBuffActiveTimer(31, 69076)
So those should be corrected already.

As for the LDW code,
    if not mod:IsDifficulty("normal10") then
        timerDominateMindCD:Start(30)
-- Sometimes 1 fails at the start, then the next will be applied 70
secs after start ?? :S
    end
This is original code from retail DBM

    timerDominateMindCD:Start(-13-delay)  -- Custom adjustment to Heroic25
    if self.Options.RemoveDruidBuff then
-- Edit to automaticly remove Mark/Gift of the Wild on entering combat
        mod:ScheduleMethod(24, "RemoveBuffs")
With the Dominate Mind timer, yes one counters the other, i could possibly
clean that up, but the reason i did it this way is that it's easier to
revert changes made if and when i try to get normal/heroic recognition
working again.
As for the G/MotW removal, what do you think is causing errors there cause
it works perfectly on Icecrown.


Op za 18 apr. 2020 om 17:43 schreef johngitboy <notifications@github.com>:

**Comment by Ayaro1** [comment]
I completely misread your comment earlier.
I missed the part where you said you did normal mode.
Yes, the timers are hard set to heroic mode so they'll be wrong for normal.
Fixing proper difficulty recognition is on my to-do list, but it's not something i'm working on right now.
Apologies for the misunderstanding.
