### ISSUE TITLE
Countdown Timer

### ISSUE THREAD

**Issue by Noob1e** [Ayaro1/DBM_Warmane_Icecrown#3]
Timer doesn't work for more than 30 seconds. It only shows a bar instead of the numbers.

![WoWScrnShot_112720_231803](https://user-images.githubusercontent.com/27544010/100523191-926c0780-31bf-11eb-91a0-7bc15b6d09b2.jpg)
![WoWScrnShot_112720_231821](https://user-images.githubusercontent.com/27544010/100523192-9435cb00-31bf-11eb-917e-5e4acaa09c2c.jpg)

**Comment by Ayaro1** [comment]
That big countdown you're showing there isn't included in my DBM. Are you using a fork or a custom WA to show that?

**Comment by Noob1e** [comment]
Maybe it's because of ElvUI or something?

**Comment by Zidras** [comment]
That is ElvUI_Enhanced

**Comment by MaelKoT** [comment]
turnoff Hook DBM ?
![image](https://user-images.githubusercontent.com/2527033/100596067-c9036880-330c-11eb-967e-ac35fbe6584c.png)

**Comment by Ayaro1** [comment]
So the source has been found and it's not DBM.
I'll close the issue.
Happy raiding!
