### ISSUE TITLE
VDW Suppressor timing incorret

### ISSUE THREAD

**Issue by firehawk2k2** [Ayaro1/DBM_Warmane_Icecrown#4]
Hi,
The timing on the announcement for suppressors on VDW is incorrect by a pretty significant amount of time.
Tested today on Warmane Icecrown.

**Comment by Ayaro1** [comment]
Hello,

I'm aware these timers are incorrect. Warmane changed the boss' timers somewhere in December last year.
Currently i'm not able to play much, if at all. Fixing this will take some time, but it will be fixed.

**Comment by Ayaro1** [comment]
Forgot to close this issue after fixing kekw
